name: NetBoard自动数据更新

on:
  schedule:
    # * is a special character in YAML so you have to quote this string分时日月星期
    - cron:  '59 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build and Run
      run: |
        cd net8.0
        ./Netboard_tools.exe
    - name: Commit and Push Output Files
      run: |
        # 配置 Git 身份
        #git config --global user.name "奈版action"
        #git config --global user.email ""
        
        # 添加、提交、推送文件
        cd net8.0
        git add out
        git commit -m "Auto-commit output files"
        git push origin main
